import SwiftUI

// Note: Colors from asset catalog (AppGreen, AppBg, etc.) are auto-generated by Xcode.
// This file contains only additional color utilities.

extension Color {
    // MARK: - Accent Colors (Static - same in both modes)
    static let appYellow = Color(hex: "F59E0B")
    static let appOrange = Color(hex: "F97316")
    static let appRed = Color(hex: "EF4444")
    static let appBlue = Color(hex: "3B82F6")
    static let appPurple = Color(hex: "8B5CF6")

    // MARK: - Score Colors
    static func scoreColor(for score: Int) -> Color {
        switch score {
        case 90...100: return .appGreen
        case 70..<90: return .appBlue
        case 50..<70: return .appYellow
        default: return .appRed
        }
    }

    // MARK: - Hex Init
    init(hex: String) {
        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var int: UInt64 = 0
        Scanner(string: hex).scanHexInt64(&int)
        let a, r, g, b: UInt64
        switch hex.count {
        case 6:
            (a, r, g, b) = (255, int >> 16, int >> 8 & 0xFF, int & 0xFF)
        case 8:
            (a, r, g, b) = (int >> 24, int >> 16 & 0xFF, int >> 8 & 0xFF, int & 0xFF)
        default:
            (a, r, g, b) = (255, 0, 0, 0)
        }
        self.init(
            .sRGB,
            red: Double(r) / 255,
            green: Double(g) / 255,
            blue: Double(b) / 255,
            opacity: Double(a) / 255
        )
    }
}
