/**
 * @module schemas
 *
 * TypeScript interfaces defining the exact JSON structures for all
 * language learning content types generated by the CLI tool.
 *
 * These schemas match the data models consumed by the Langu iOS app.
 */

// ---------------------------------------------------------------------------
// Difficulty
// ---------------------------------------------------------------------------

/** Difficulty levels used across all content types. */
export type Difficulty = "beginner" | "intermediate" | "advanced";

// ---------------------------------------------------------------------------
// Units & Lessons
// ---------------------------------------------------------------------------

/** A single pronunciation lesson within a unit. */
export interface Lesson {
  /** Unique lesson identifier. */
  id: number;
  /** The parent unit this lesson belongs to. */
  unitId: number;
  /** Display order within the unit (1-based). */
  order: number;
  /** Emoji representing the lesson topic. */
  emoji: string;
  /** Short English title for the lesson. */
  title: string;
  /** The Korean text to practice. */
  korean: string;
  /** Romanization of the Korean text (Revised Romanization). */
  romanization: string;
  /** English translation. */
  translation: string;
  /** Difficulty level. */
  difficulty: Difficulty;
  /** A pronunciation hint focusing on sounds that are hard for learners. */
  hint: string;
}

/** A thematic unit containing multiple lessons. */
export interface LessonUnit {
  /** Unique unit identifier. */
  id: number;
  /** Emoji representing the unit theme. */
  emoji: string;
  /** English title for the unit. */
  title: string;
  /** Short description of what the unit covers. */
  description: string;
  /** Difficulty level. */
  difficulty: Difficulty;
  /** Ordered list of lessons within this unit. */
  lessons: Lesson[];
}

/** Top-level wrapper for the units JSON file. */
export interface UnitsFile {
  units: LessonUnit[];
}

// ---------------------------------------------------------------------------
// Stories
// ---------------------------------------------------------------------------

/** A single sentence within a story. */
export interface StorySentence {
  /** Sentence index within the story (1-based). */
  id: number;
  /** Korean text of the sentence. */
  korean: string;
  /** Romanization (Revised Romanization). */
  romanization: string;
  /** English translation. */
  translation: string;
}

/** A short story composed of multiple sentences for reading practice. */
export interface Story {
  /** Unique story identifier. */
  id: number;
  /** English title. */
  title: string;
  /** Korean title. */
  titleKorean: string;
  /** Emoji representing the story theme. */
  emoji: string;
  /** Difficulty level. */
  difficulty: Difficulty;
  /** Ordered list of sentences. */
  sentences: StorySentence[];
}

/** Top-level wrapper for the stories JSON file. */
export interface StoriesFile {
  stories: Story[];
}

// ---------------------------------------------------------------------------
// Themes (Free Talk)
// ---------------------------------------------------------------------------

/** A conversation theme for free-talk practice sessions. */
export interface Theme {
  /** Unique string identifier (kebab-case). */
  id: string;
  /** Emoji representing the theme. */
  emoji: string;
  /** English name. */
  name: string;
  /** Korean name. */
  koreanName: string;
  /** Short description of the theme in English. */
  description: string;
  /** Suggested vocabulary keywords for this theme. */
  keywords: string[];
  /** Difficulty level. */
  difficulty: Difficulty;
  /** Recommended minimum session duration in seconds. */
  minDurationSeconds: number;
  /** Example Korean sentences a learner might use. */
  exampleSentences: string[];
}

/** Top-level wrapper for the themes JSON file. */
export interface ThemesFile {
  themes: Theme[];
}

// ---------------------------------------------------------------------------
// Generation options passed from the CLI to the generator
// ---------------------------------------------------------------------------

/** Options shared by all generation methods. */
export interface GenerationOptions {
  /** The learner's native language (e.g. "English"). */
  nativeLanguage: string;
  /** The language being learned (e.g. "Korean"). */
  targetLanguage: string;
}

/** Options specific to unit/lesson generation. */
export interface UnitGenerationOptions extends GenerationOptions {
  /** Number of units to generate. @default 6 */
  unitCount: number;
  /** Number of lessons per unit. @default 5 */
  lessonsPerUnit: number;
}

/** Options specific to story generation. */
export interface StoryGenerationOptions extends GenerationOptions {
  /** Number of stories to generate. @default 5 */
  storyCount: number;
}

/** Options specific to theme generation. */
export interface ThemeGenerationOptions extends GenerationOptions {
  /** Number of themes to generate. @default 6 */
  themeCount: number;
}
